name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  unit-test:
    name: Unit Test
    runs-on: macos-15
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.4.app/Contents/Developer"

    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run Test
        run: |
          xcodebuild test \
            -scheme CalcPicker \
            -destination "platform=macOS,arch=arm64" \
            -resultBundlePath TestResults/unit_test_result_bundle | \
            xcbeautify && exit ${PIPESTATUS[0]}
